baseurl = "https://sujittripathy.github.io"
languageCode = "en"
title = "SUJIT TRIPATHY"
theme = "hemingway"
copyright = "Powered by <a href=\"https://gohugo.io/\">Hugo&copy</a> 2018"
#disqusShortname = "sujit_tripathy"
googleAnalytics = ""
paginate = 5	

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://www.linkedin.com/in/sujittripathy"
fa_icon = "fa-linkedin"

[[params.social]]
url = "https://github.com/sujittripathy"
fa_icon = "fa-github-square"

[[params.social]]
url = "https://twitter.com/sujittri"
fa_icon = "fa-twitter-square"

#[[params.social]]
#url = "/index.xml"
#fa_icon = "fa-rss"